services:
  indico:
    #build: ..
    image: codeberg.org/0x2321/indico-docker:3.3
    env_file: .env
    volumes:
      - data:/data
      - ./indico.conf:/etc/indico.conf:ro
     # - ./shibboleth2.xml:/etc/shibboleth/shibboleth2.xml:ro # only needed with shibboleth
     # - latex:/opt/indico/texmf # only needed for latex support
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    volumes:
      - redis:/data

  postgres:
    image: postgres:15-bookworm
    environment:
      - POSTGRES_DB=${INDICO_POSTGRES_DB}
      - POSTGRES_USER=${INDICO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${INDICO_POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  data:
  # latex:
  redis:
  postgres: