services:
  indico:
    # build: ..
    image: codeberg.org/0x2321/indico-docker:latest
    env_file: .env
    volumes:
      - data:/data
      - web:/opt/indico/static
      - ./indico.conf:/etc/indico.conf:ro
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    volumes:
      - redis:/data

  postgres:
    image: postgres:15-bookworm
    environment:
      - POSTGRES_DB=${INDICO_POSTGRES_DB}
      - POSTGRES_USER=${INDICO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${INDICO_POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  caddy:
    image: caddy:alpine
    depends_on:
      - indico
    ports:
      - 8080:80
    volumes:
      - web:/opt/indico/static
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

volumes:
  data:
  web:
  redis:
  postgres: