REDIS_CACHE_URL = 'redis://redis:6379/0'
CELERY_BROKER   = 'redis://redis:6379/1'

# Change these emails to something sensible
NO_REPLY_EMAIL = 'noreply@example.invalid'
SUPPORT_EMAIL = 'suppport@example.invalid'

# Specify the plugins you need here
PLUGINS = {}