Listen 8080
PidFile /tmp/httpd.pid
ErrorLog /dev/stderr
CustomLog /dev/stdout combined
ServerName _

<VirtualHost *:8080>
    DocumentRoot "/var/empty"

    # XSendFile on
    # XSendFilePath /opt/indico
    LogLevel error
    ServerSignature Off

    <LocationMatch "^(/Shibboleth\.sso|/login/shib-sso/shibboleth)">
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        ShibExportAssertion Off
        Require valid-user
    </LocationMatch>

    AliasMatch "^/(images|fonts)(.*)/(.+?)(__v[0-9a-f]+)?\.([^.]+)$" "/opt/indico/static/$1$2/$3.$5"
    AliasMatch "^/(css|dist|images|fonts)/(.*)$" "/opt/indico/static/$1/$2"
    Alias /robots.txt /opt/indico/static/robots.txt

    # SetEnv UWSGI_SCHEME https
    ProxyPass / unix:/tmp/uwsgi.sock|uwsgi://localhost/

    <Directory /opt/indico>
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>