import os

# Directories
LOG_DIR = '/var/log/indico'
CACHE_DIR = '/var/cache/indico'
TEMP_DIR = '/var/tmp/indico'

# Logging
LOGGING_CONFIG_FILE = '/opt/indico/logging.yaml'

# Storage
STORAGE_BACKENDS = {'default': f'fs:{os.environ.get('STORAGE_DIR', '/data')}'}
ATTACHMENT_STORAGE = 'default'

# Database
SQLALCHEMY_DATABASE_URI = f'postgresql://{os.environ["PGUSER"]}:{os.environ["PGPASSWORD"]}@{os.environ["PGHOST"]}:5432/{os.environ["PGDATABASE"]}'

# LaTeX
if os.path.exists('/usr/bin/xelatex'):
    XELATEX_PATH = '/usr/bin/xelatex'

# System
SECRET_KEY = f'{os.environ["SECRET_KEY"]}'
BASE_URL = f'{os.environ["BASE_URL"]}'
USE_PROXY = True

del os

