version: 1

root:
  level: INFO
  handlers: [console]

loggers:
  indico:
    handlers: [console]
  celery:
    handlers: [console]

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    filters: [indico, celery, other]

formatters:
  default:
    format: '%(asctime)s  %(levelname)-7s  %(request_id)s  %(user_id)-6s  %(name)-25s %(message)s'

filters:
  indico:
    name: indico
  celery:
    name: celery
  other:
    (): indico.core.logger.BlacklistFilter
    names: [indico, celery]